# Generated by Django 5.1.4 on 2025-01-21 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
    ]
