# Generated by Django 5.1.4 on 2025-02-04 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='producto.vendedor')),
            ],
        ),
    ]
